/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002023",
        "on-tertiary-container": "#006d75",
        "surface-variant": "#e9e2d4",
        "inverse-primary": "#e5c44b",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e9e2d4",
        "on-secondary-fixed-variant": "#004e60",
        "on-error": "#ffffff",
        "background-alt": "#F4F4F4",
        "surface-bright": "#fff8ef",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f8f0e2",
        "surface-container-low": "#fbf3e5",
        "inverse-surface": "#343027",
        "primary": "#715c00",
        "error": "#ba1a1a",
        "on-surface-variant": "#4c4635",
        "secondary-fixed-dim": "#47d6ff",
        "surface-container": "#f5eddf",
        "on-surface": "#1e1b13",
        "on-secondary-container": "#00566a",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#efe7da",
        "on-secondary-fixed": "#001f28",
        "primary-container": "#ffdc60",
        "on-primary-container": "#756000",
        "on-background": "#1e1b13",
        "tertiary-container": "#6df1ff",
        "tertiary-fixed": "#86f3ff",
        "outline": "#7e7763",
        "surface-tint": "#715c00",
        "accent-pink": "#FFA2D2",
        "tertiary-fixed-dim": "#50d8e6",
        "secondary": "#00677f",
        "primary-fixed-dim": "#e5c44b",
        "primary-fixed": "#ffe17a",
        "accent-orange": "#FF4B13",
        "surface-dim": "#e0d9cc",
        "surface": "#FFFFFF",
        "outline-variant": "#cfc6af",
        "accent-purple": "#7E30E1",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#554500",
        "tertiary": "#006971",
        "background": "#fff8ef",
        "on-tertiary-fixed-variant": "#004f55",
        "on-primary-fixed": "#231b00",
        "secondary-container": "#00d2ff",
        "secondary-fixed": "#b6ebff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        lg: "24px",
        xs: "4px",
        xl: "48px",
        md: "16px",
        margin: "24px",
        sm: "8px",
      },
      fontFamily: {
        "headline-main-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-bold": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-main": ["'Plus Jakarta Sans'", "Inter", "sans-serif"],
        "heading-card": ["'Plus Jakarta Sans'", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-main-mobile": ["40px", { lineHeight: "1.1", fontWeight: "800" }],
        "body-md": ["0.95rem", { lineHeight: "1.5", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-main": ["3.5rem", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "800" }],
        "heading-card": ["1.5rem", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
